Repository hash-define-organization/Hacktober-Fest-2021, pull requests merged in 2021-10, with the labels that each got.

#2 added roadmap for android dev kotlin
  MobileDev/Kotlin/ROADMAP.md
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#43 Update README.md
  README.md
Labels: good first issue, hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#48 Added the basic code for the script
  WebDev/Backend/Directory-Explorer/index.js
  WebDev/Backend/Directory-Explorer/package.json
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#29 Laid the Foundation of Hashdefine Website
  WebDev/HTML-CSS/images/3new.png
  WebDev/HTML-CSS/images/hacktoberfestbanner.jpg
  WebDev/HTML-CSS/images/hashdefine.jpg
  WebDev/HTML-CSS/images/hashdefine_text.png
  WebDev/HTML-CSS/index.html
  WebDev/HTML-CSS/style.css
  WebDev/HTML-CSS/utility.css
Labels: good first issue, hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#39 added 2-D Matrix Spiral Problem
  DSA/Cpp/2_d_Spiral_matrix_problem.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#98 Code Player(JS bin clone)
  DSA/Java/Program to check whether the sentence is pangram
  Design.html
  WebDev/HTML-CSS/Code Player(JS bin clone)
  dd.jpg
Labels: hacktoberfest, hacktoberfest2021

#114 Completed reverse integer(DSA) #33
  DSA/Cpp/reverse_integer.cpp
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#7 Added Grocery Web application
  WebDev/Frontend/React/GroceryStore/.gitignore
  WebDev/Frontend/React/GroceryStore/README.md
  WebDev/Frontend/React/GroceryStore/firebase.json
  WebDev/Frontend/React/GroceryStore/package-lock.json
  WebDev/Frontend/React/GroceryStore/package.json
  WebDev/Frontend/React/GroceryStore/public/favicon.ico
  WebDev/Frontend/React/GroceryStore/public/index.html
  WebDev/Frontend/React/GroceryStore/public/logo192.png
  WebDev/Frontend/React/GroceryStore/public/logo512.png
  WebDev/Frontend/React/GroceryStore/public/manifest.json
  WebDev/Frontend/React/GroceryStore/public/robots.txt
  WebDev/Frontend/React/GroceryStore/public/to-do-list.ico
  WebDev/Frontend/React/GroceryStore/src/App.css
  WebDev/Frontend/React/GroceryStore/src/App.js
  WebDev/Frontend/React/GroceryStore/src/App.test.js
  WebDev/Frontend/React/GroceryStore/src/List.css
  WebDev/Frontend/React/GroceryStore/src/List.js
  WebDev/Frontend/React/GroceryStore/src/index.css
  WebDev/Frontend/React/GroceryStore/src/index.js
  WebDev/Frontend/React/GroceryStore/src/logo.svg
  WebDev/Frontend/React/GroceryStore/src/reportWebVitals.js
  WebDev/Frontend/React/GroceryStore/src/setupTests.js
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#119 Url shortner/python
  Other/Url-Shortner/app.py
  Other/Url-Shortner/static/css/main.css
  Other/Url-Shortner/static/js/main.js
  Other/Url-Shortner/templates/index.html
  Other/Url-Shortner/urls.csv
Labels: enhancement, hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#86 Added solution for max path sum
  DSA/Cpp/Trees/MAX_PATH_SUM.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#171 Update README.md and made some major changes
  README.md
  circle_cropped.png
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#100 A program for printing the sub sequences of a given string using recursion
  DSA/Cpp/Recursion_and_Backtracking/Subsequences.cpp
  DSA/Cpp/Recursion_and_Backtracking/TowerOfHanoi.cpp
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#120 Create README.md
  DSA/Cpp/Linked_List/linked_list.cpp
  DSA/Cpp/Strings/README.md
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#181 fixed the images folder and readMe Links
  README.md
  readmeSrc/circle_cropped.png
  readmeSrc/dd.jpg
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#186 Added codebase for Starbucks Clone
  WebDev/Frontend/Starbucks Clone/PngItem_1124167.png
  WebDev/Frontend/Starbucks Clone/PngItem_5445259.png
  WebDev/Frontend/Starbucks Clone/address.css
  WebDev/Frontend/Starbucks Clone/address.html
  WebDev/Frontend/Starbucks Clone/arrow-address-back_icon-icons.com_54065.png
  WebDev/Frontend/Starbucks Clone/bg.jpg
  WebDev/Frontend/Starbucks Clone/cafe-iced-coffee-latte-starbucks-coffee-f797b13c2cc4cc22009de8bb5f332c63.png
  WebDev/Frontend/Starbucks Clone/cappiciunno.png
  WebDev/Frontend/Starbucks Clone/cart.css
  WebDev/Frontend/Starbucks Clone/cart.html
  WebDev/Frontend/Starbucks Clone/cloud1.png
  WebDev/Frontend/Starbucks Clone/cloud2.png
  WebDev/Frontend/Starbucks Clone/cloud3.png
  WebDev/Frontend/Starbucks Clone/cold-coffee.png
  WebDev/Frontend/Starbucks Clone/facebook.png
  WebDev/Frontend/Starbucks Clone/forest.png
  WebDev/Frontend/Starbucks Clone/icons8-shopping-cart-64.png
  WebDev/Frontend/Starbucks Clone/img-1.jpg
  WebDev/Frontend/Starbucks Clone/img1.png
  WebDev/Frontend/Starbucks Clone/img2.png
  WebDev/Frontend/Starbucks Clone/img3.png
  WebDev/Frontend/Starbucks Clone/index.html
  WebDev/Frontend/Starbucks Clone/instagram.png
  WebDev/Frontend/Starbucks Clone/kisspng-coffee-adhesive-tape-starbucks-frappuccino-sticker-starbucks-tumblr-transparent-amp-png-clipart-fre-5ca05b44843c07.3284031215540129965416.png
  WebDev/Frontend/Starbucks Clone/kisspng-latte-green-tea-iced-tea-matcha-starbucks-coffee-icedcoffee-tea-tumblr-icecoffee-s-5d16e66ddcb633.393205681561781869904.png
  WebDev/Frontend/Starbucks Clone/logo.png
  WebDev/Frontend/Starbucks Clone/menu.css
  WebDev/Frontend/Starbucks Clone/menu.html
  WebDev/Frontend/Starbucks Clone/sign.css
  WebDev/Frontend/Starbucks Clone/sign.html
  WebDev/Frontend/Starbucks Clone/starbucks_logo_icon_170704.ico
  WebDev/Frontend/Starbucks Clone/starbucks_logo_icon_170704.png
  WebDev/Frontend/Starbucks Clone/style.css
  WebDev/Frontend/Starbucks Clone/thumb1.png
  WebDev/Frontend/Starbucks Clone/thumb2.png
  WebDev/Frontend/Starbucks Clone/thumb3.png
  WebDev/Frontend/Starbucks Clone/twitter.png
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#182 Added survey form
  WebDev/HTML-CSS/SurveyForm/survey.css
  WebDev/HTML-CSS/SurveyForm/surveyForm.html
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#144 Computer Networking Problems/ Algo
  Computer Networks/ByteStuffing.cpp
  Computer Networks/CRC.cpp
  Computer Networks/DistanceVectorRoutingProtocol.cpp
  Computer Networks/LRC.cpp
  Computer Networks/OSI_Model.cpp
  OS Concept/OS/FirstComeFirstServe.cpp
  OS Concept/OS/NonPremetiveScheduling.cpp
  OS Concept/OS/NonPremetiveShortestJobFirst.cpp
  OS Concept/OS/PremetiveShortestJobFirst.cpp
  OS Concept/OS/PriorityPremetiveScheduling.cpp
  OS Concept/OS/RoundRobinScheduling.cpp
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#198 #197 Added Portfolio_Blog Webpage
  WebDev/HTML-CSS/CVT/ReadMe.md
  WebDev/HTML-CSS/CVT/about.html
  WebDev/HTML-CSS/CVT/bloglist.html
  WebDev/HTML-CSS/CVT/blogpost.html
  WebDev/HTML-CSS/CVT/img/1.jpg
  WebDev/HTML-CSS/CVT/img/2.jpg
  WebDev/HTML-CSS/CVT/img/about-banner.jpg
  WebDev/HTML-CSS/CVT/img/banner.png
  WebDev/HTML-CSS/CVT/img/blog-banner.jpg
  WebDev/HTML-CSS/CVT/img/favicon.ico
  WebDev/HTML-CSS/CVT/img/logo.png
  WebDev/HTML-CSS/CVT/img/team.jpg
  WebDev/HTML-CSS/CVT/index.html
  WebDev/HTML-CSS/CVT/main.js
  WebDev/HTML-CSS/CVT/style.css
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#173 Added Tours And Travel Animated website
  WebDev/HTML-CSS/Tours And Travel/README.md
  WebDev/HTML-CSS/Tours And Travel/css/style.css
  WebDev/HTML-CSS/Tours And Travel/images/taj.jpg
  WebDev/HTML-CSS/Tours And Travel/index.html
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#199 Sign Up Page by Shreya20-web
  WebDev/HTML-CSS/Sign Up page/12_form_styling.html
  WebDev/HTML-CSS/Sign Up page/SignUppage.PNG
  WebDev/HTML-CSS/Sign Up page/SignUppage2.PNG
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted, webdev

#151 made js folder to uload js scripts
  javascript/promise-sample.js
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#118 sorting algorithms
  DSA/Cpp/Sorting-Algorithms/Bubble-Sort.txt
  DSA/Cpp/Sorting-Algorithms/Insertion-Sort.txt
  DSA/Cpp/Sorting-Algorithms/Selection-Sort.txt
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#102 added nCr mod (1e9+7) code in DSA/CPP
  DSA/Cpp/n_C_r_mod_P.cpp
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#124 Created a single styled Html Page
  WebDev/HTML-CSS/Styled Page/index.html
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#157 I added files of logistic regression algorithm in the AI & Ml section
  ML-AI/Logistic Regression/Admission_Predict.csv
  ML-AI/Logistic Regression/Logistic Regression.ipynb
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#172 resolve issue #21 (number conversions)
  DSA/Java/Number_Theory/Binary_to_decimal.java
  DSA/Java/Number_Theory/Decimal_to_Binary.java
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#34 Reverse a number
  DSA/Python/Reverse an integer
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#212 Added basic codes for Gtkmm
  Gtkmm-Codes-CPP/CheckButton/checkButton.cpp
  Gtkmm-Codes-CPP/CheckButton/checkButton.h
  Gtkmm-Codes-CPP/Introductory101/hello-world-gtk.c
  Gtkmm-Codes-CPP/Introductory101/hello.c
  Gtkmm-Codes-CPP/Introductory101/packing.c
  Gtkmm-Codes-CPP/Introductory101/simple.cc
  Gtkmm-Codes-CPP/Introductory101/testing.cpp
  Gtkmm-Codes-CPP/button/button.cpp
  Gtkmm-Codes-CPP/button/button.h
Labels: hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#204 Added Camera Application under Web Dev section
  WebDev/Frontend/Camera Application/dbScript.js
  WebDev/Frontend/Camera Application/gallery.css
  WebDev/Frontend/Camera Application/gallery.html
  WebDev/Frontend/Camera Application/index.html
  WebDev/Frontend/Camera Application/script.js
  WebDev/Frontend/Camera Application/style.css
Labels: enhancement, hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#201 Create domaintoipconverter.sh
  CyberSec/domaintoipconverter.sh
Labels: enhancement, hacktoberfest, hacktoberfest2021, hacktoberfest-accepted

#160 Detect, prevent and recover MITM attacks
  CyberSec/Anti-arp system.py
Labels: enhancement, hacktoberfest, hacktoberfest2021, hacktoberfest-accepted
